global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 如果你的 Go API 有 metrics 端点，可以添加
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis 监控（如果有 redis_exporter）
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']

  # PostgreSQL 监控（如果有 postgres_exporter）
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']